### ISSUE TITLE
Error when installing in setup.cfg

### ISSUE THREAD

**Issue by GeriTopore** [mmonajem/pyccapt#9]
When I try to setup the package by running `pip install -e .` I get the following error:

```py
distutils.errors.DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'include_package_data'
```
this is in a fresh conda environment running Python 3.9.

Full error message is as follows:
```py
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\commands\install.py", line 294, in run
    options.use_user_site = decide_user_install(
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\commands\install.py", line 713, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\commands\install.py", line 659, in site_packages_writable
    for d in set(get_lib_location_guesses(root=root, isolated=isolated))
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\commands\install.py", line 645, in get_lib_location_guesses
    scheme = get_scheme(
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\locations\__init__.py", line 249, in get_scheme
    old = _distutils.get_scheme(
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\locations\_distutils.py", line 141, in get_scheme
    scheme = distutils_scheme(dist_name, user, home, root, isolated, prefix)
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\site-packages\pip\_internal\locations\_distutils.py", line 66, in distutils_scheme
    obj = d.get_command_obj("install", create=True)
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\distutils\dist.py", line 868, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "C:\Users\gerit\mambaforge\envs\pyccapt\lib\distutils\dist.py", line 910, in _set_command_options
    raise DistutilsOptionError(
distutils.errors.DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'include_package_data'
```

**Comment by GeriTopore** [comment]
Seems to have been fixed with the most recent changes to the setup files. The install now is successful.

**Comment by mmonajem** [comment]
I'm sorry for the delay in getting back to you. we've fixed the problem with our latest commit! We're constantly working on improving our code. If you run into any more issues, feel free to get in touch with us. 😊
